import {StyleSheet} from 'react-native';
import Util from './../../js/util';
import HomeStyle from "../home/HomeStyle";

const classifyStyle = StyleSheet.create({
    //客户详情页面
    topBox:{
        backgroundColor:'#429cfd',
        paddingLeft:11,
        paddingRight:11,
        paddingTop:16
    },
    writeText:{
        color:'#fff',
        fontWeight:"400"
    },
    phone:{
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:3,
        marginTop:15
    },
    phoneImage:{
        marginLeft:17
    },
    titleName:{
        flexDirection:'row',
        alignItems:'center'
    },
    blueText:{
        backgroundColor:'#fff',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        width:40,
        height:16,
        borderRadius:8,
        marginLeft:5
    },
    titleText:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'flex-start'
    },
    money:{
        alignItems:'center'
    },
    topCenterBox:{
        width:'100%',
        flexDirection:'row',
        justifyContent:'space-around',
        alignItems:'center',
        backgroundColor:'#fff',
        alignSelf:'center',
        marginTop:23,
        paddingLeft:11,
        paddingRight:11,
        paddingTop:25,
        paddingBottom:20,
        borderRadius:10
    },
    test:{
        backgroundColor:'#f8f8fa',
        position:'absolute',
        bottom:0,
        right:0,
        width:Util.size.width,
        height:26
    },
    line:{
        width:1,
        height:34,
        backgroundColor:'#cccccc'
    },
    textB:{
        color:'#4a4a4a',
        fontWeight:'400'
    },
    textC:{
        color:'#4a4a4a',
        fontWeight:'400',
        marginTop:5
    },
    ContentDetails:{
        marginTop:20,
        paddingLeft:11,
        paddingRight:11,
    },
    ContentDetailsItem:{
        paddingLeft:14,
        paddingRight:16,
        backgroundColor:"#fff",
        marginBottom:23,
        // paddingTop:10,
        // paddingBottom:15,
        borderRadius:10
    },
    Item01:{
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingTop:9,
        paddingBottom:9,
        borderBottomColor:'#e9eaee',
        borderBottomWidth:1,
    },
    Item01Tilte:{
        marginLeft:8,
        color:'#ccc',
    },
    ItemTextBox:{
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:17,
        paddingTop:9,
        paddingBottom:9,
        borderBottomColor:'#e9eaee',
        borderBottomWidth:1,
    },
    ItemTextBoxLast:{
        borderBottomColor:'#fff',
        borderBottomWidth:0,
    },
    ItemText:{
        color:'#4a4a4a'
    },
    buttonBox:{
        flex:1,
        justifyContent:'center',
        height:55,
        backgroundColor:'#50acff'
    },
    btnText:{
        color:'#fff',
        textAlign:'center',
    },
})
export default classifyStyle;